language: c
compiler:
  - clang
  - gcc
env:
  matrix:
    - USELIBCONFIG= USELIBWRAP= USELIBCAP=
    - USELIBCONFIG=1 USELIBWRAP=1 USELIBCAP=1
  global:
    - cflags=-Wall -Werror

before_script:
  - sudo apt-get install libconfig-dev
script:
  - make USELIBCONFIG=$USELIBCONFIG USELIBWRAP=$USELIBWRAP USELIBCAP=$USELIBCAP
