language: c
compiler:
  - clang
  - gcc
env:
  matrix:
    - USELIBCONFIG= USELIBWRAP= USELIBCAP=
    - USELIBCONFIG=1 USELIBWRAP=1 USELIBCAP=1
  global:
    - "CFLAGS=-Wall -Werror"

before_script:
  - if [[ -n "${USELIBCONFIG}" ]]; then
      sudo apt-get install libconfig-dev;
    fi
  - if [[ -n "${USELIBCAP}" ]]; then
      sudo apt-get install libcap-dev;
    fi
  - if [[ -n "${USELIBWRAP}" ]]; then
      sudo apt-get install libwrap-dev;
    fi
script:
  - make USELIBCONFIG=$USELIBCONFIG USELIBWRAP=$USELIBWRAP USELIBCAP=$USELIBCAP
notification:
  mails: false
